### ISSUE TITLE
Create room fails

### ISSUE THREAD

**Issue by wwwclaes** [ThomasOliver545/real-time-chat-nestjs-angular#2]
I just watched your great Youtube-videos and I am trying to setup a local environment (outside of Docker) for debugging and better understanding of the application code. However, I always get this error when trying to create a room:

```
[Nest] 18481  - 05/20/2022, 10:04:24 AM   ERROR [WsExceptionsHandler] duplicate key value violates unique constraint "PK_9a71b6e39db119a6e2c11925445"
QueryFailedError: duplicate key value violates unique constraint "PK_9a71b6e39db119a6e2c11925445"
    at QueryFailedError.TypeORMError [as constructor] (/home/wwwclaes/src/angular-nestjs/real-time-chat-nestjs-angular/api/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/home/wwwclaes/src/angular-nestjs/real-time-chat-nestjs-angular/api/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/home/wwwclaes/src/angular-nestjs/real-time-chat-nestjs-angular/api/src/driver/postgres/PostgresQueryRunner.ts:247:19)
    at step (/home/wwwclaes/src/angular-nestjs/real-time-chat-nestjs-angular/api/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/home/wwwclaes/src/angular-nestjs/real-time-chat-nestjs-angular/api/node_modules/tslib/tslib.js:124:57)
    at rejected (/home/wwwclaes/src/angular-nestjs/real-time-chat-nestjs-angular/api/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Same problem using MySQL but with a slightly different error message:

```
[Nest] 19381  - 05/20/2022, 10:13:35 AM   ERROR [WsExceptionsHandler] ER_DUP_ENTRY: Duplicate entry '1-1' for key 'room_entity_users_user_entity.PRIMARY'
QueryFailedError: ER_DUP_ENTRY: Duplicate entry '5-1' for key 'room_entity_users_user_entity.PRIMARY'
    at QueryFailedError.TypeORMError [as constructor] (/home/wwwclaes/src/angular-nestjs/real-time-chat-nestjs-angular/api/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/home/wwwclaes/src/angular-nestjs/real-time-chat-nestjs-angular/api/src/error/QueryFailedError.ts:9:9)
    at Query.<anonymous> (/home/wwwclaes/src/angular-nestjs/real-time-chat-nestjs-angular/api/src/driver/mysql/MysqlQueryRunner.ts:183:37)
    at Query.<anonymous> (/home/wwwclaes/src/angular-nestjs/real-time-chat-nestjs-angular/api/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/wwwclaes/src/angular-nestjs/real-time-chat-nestjs-angular/api/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/wwwclaes/src/angular-nestjs/real-time-chat-nestjs-angular/api/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/wwwclaes/src/angular-nestjs/real-time-chat-nestjs-angular/api/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/wwwclaes/src/angular-nestjs/real-time-chat-nestjs-angular/api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/wwwclaes/src/angular-nestjs/real-time-chat-nestjs-angular/api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/wwwclaes/src/angular-nestjs/real-time-chat-nestjs-angular/api/node_modules/mysql/lib/protocol/Parser.js:43:10)

```

Do you happen to know what might be causing this issue?

**Comment by TommiCodes** [comment]
Seems like you violate the unique constraint.
I would need to see your code to answer this
